/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import negocio.Agendamento;
import negocio.AgendamentoHistorico;
import negocio.Cliente;
import negocio.Comissao;
import negocio.Funcionario;
import negocio.Sessao;
import persistencia.AgendamentoDAO;
import persistencia.IAgendamentoDAO;
import persistencia.ClienteDAO;
import persistencia.ComissaoDAO;
import persistencia.IAgendamentoHistoricoDAO;
import persistencia.AgendamentoHistoricoDAO;
import persistencia.IClienteDAO;
import persistencia.IComissaoDAO;

/**
 *
 * @author joaos
 */
public class fmCadastroAtendimento extends javax.swing.JInternalFrame {
    /**
     * Creates new form fmCadastroAtendimento
     */
    public fmCadastroAtendimento(Funcionario Funcionario) {
        initComponents();
        cbFuncionario.addItem(Funcionario);
        cbFuncionario.setSelectedItem(Funcionario);
        txtPorcentagemComissao.setText(String.valueOf(Funcionario.getComissaoPorcentagemPadrao()));
        geraDadosComboCliente();
    }
    
    public fmCadastroAtendimento(Funcionario funcionario, Agendamento agendamento) {

        initComponents();
        geraDadosComboCliente();
        IClienteDAO dao = new ClienteDAO();
        Cliente cliente = dao.buscarPorID(agendamento.getIdCliente());
        cbNomeCliente.setSelectedItem(cliente);
        cbFuncionario.addItem(funcionario);
        cbFuncionario.setSelectedItem(funcionario);
        txtPorcentagemComissao.setText(String.valueOf(funcionario.getComissaoPorcentagemPadrao()));
        txtValor.setText(String.valueOf(agendamento.getValor()));
        txtDescricao.setText(agendamento.getDescricao());
        txtPorcentagemComissao.setText(String.valueOf(agendamento.getPorcentagemComissao()));
        txtData.setCalendar(agendamento.getData());
        cbHorario.setSelectedItem(agendamento.getHora());
        txtObservacao.setText(agendamento.getObservacao());
        txtCodigo.setText(String.valueOf(agendamento.getId()));
        btFinalizarAtendimento.setEnabled(true);

        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btFinalizarAtendimento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtDescricao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPorcentagemComissao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cbHorario = new javax.swing.JComboBox<>();
        txtData = new com.toedter.calendar.JDateChooser();
        cbFuncionario = new javax.swing.JComboBox<>();
        cbNomeCliente = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Cadastro de Atendimento");

        jLabel1.setText("Horario:");

        jLabel7.setText("Codigo:");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCodigo.setText("00000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        jLabel2.setText("Observacao:");

        jLabel5.setText("Cliente:");

        btFinalizarAtendimento.setText("Finalizar Atendimento");
        btFinalizarAtendimento.setEnabled(false);
        btFinalizarAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarAtendimentoActionPerformed(evt);
            }
        });

        jLabel3.setText("Data:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviço"));

        jLabel10.setText("Descrição:");

        jLabel11.setText("Valor:");

        jLabel12.setText("Porcentagem comissao");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPorcentagemComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtPorcentagemComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel6.setText("Funcionario:");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00" }));
        cbHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHorarioActionPerformed(evt);
            }
        });

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbFuncionario.setEnabled(false);

        cbNomeCliente.setToolTipText("");
        cbNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomeClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btFinalizarAtendimento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbFuncionario, 0, 215, Short.MAX_VALUE)
                                    .addComponent(cbNomeCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(cbHorario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFinalizarAtendimento)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geraDadosComboCliente()
    {
        IClienteDAO dao = new ClienteDAO();
        
        
        for (Cliente c: dao.listarTodos())
        {
            cbNomeCliente.addItem(c);
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int valor = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja salvar?", "Sistema Salão de Beleza", 1);
        if (valor ==0)
        {
            Integer IdCliente;
            Integer IdFuncionario;
            Calendar Data;
            String Descricao;
            float Valor;
            String Observacao;
            int PorcentagemComissao;
            
            Cliente cliente = (Cliente) cbNomeCliente.getSelectedItem();
            IdCliente = cliente.getId();
            Funcionario funcionario = (Funcionario)cbFuncionario.getSelectedItem();
            IdFuncionario = funcionario.getId();

            Data = txtData.getCalendar();

            String Horario = (String) cbHorario.getSelectedItem();

            Descricao = txtDescricao.getText();

            Valor = Float.parseFloat(txtValor.getText());

            Observacao = txtObservacao.getText();

            PorcentagemComissao = Integer.parseInt(txtPorcentagemComissao.getText());
            IAgendamentoDAO dao = new AgendamentoDAO();
            if (txtCodigo.getText() == "00000") {
                Agendamento agendamento = new Agendamento(IdCliente, IdFuncionario, Data, Horario, Descricao, Valor, Observacao, PorcentagemComissao) ;
                dao.adiciona(agendamento);
                JOptionPane.showMessageDialog(null, "Os dados foram gravados");
                salvaHistorico("Atendiemento criado");

            }else
            {
                Agendamento agendamento = new Agendamento(Integer.parseInt(txtCodigo.getText()),IdCliente, IdFuncionario, Data, Horario, Descricao, Valor, Observacao, PorcentagemComissao) ;
                dao.atualiza(agendamento);
                JOptionPane.showMessageDialog(null, "Os dados foram atualizados");
                salvaHistorico("Atendimento atualizado");
            
            }
            
            //limpar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHorarioActionPerformed

    private void cbNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNomeClienteActionPerformed

    private void salvaHistorico(String descricao)
    {
        IAgendamentoHistoricoDAO dao = new AgendamentoHistoricoDAO();
        AgendamentoHistorico agendamentoHistorico = new AgendamentoHistorico(Sessao.getIdUsuario(), descricao);
        dao.adiciona(agendamentoHistorico);
    }    
    private void btFinalizarAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarAtendimentoActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Finalizar o atendimento?", "Sistema Salão de Beleza", 1);
        if (valor ==0){
            IAgendamentoDAO dao = new AgendamentoDAO();
            Agendamento agendamento = dao.buscarPorID(Integer.parseInt(txtCodigo.getText()));
            agendamento.setIndFinalizado(true);
            dao.atualiza(agendamento);

            Integer idAgendamento = agendamento.getId();
            Integer idFuncionario = agendamento.getIdFuncionario();
            Float Valor = (agendamento.getPorcentagemComissao()/100.0f) * agendamento.getValor();


            Comissao comissao = new Comissao(idFuncionario, idAgendamento, Valor);
            IComissaoDAO comissaodao = new ComissaoDAO();

            comissaodao.adiciona(comissao);
            JOptionPane.showMessageDialog(null, "Atendimento finalizado!");
            salvaHistorico("Atendimento Finalizado");
            this.dispose();
        }
        
        
    }//GEN-LAST:event_btFinalizarAtendimentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizarAtendimento;
    private javax.swing.JComboBox<Object> cbFuncionario;
    private javax.swing.JComboBox<String> cbHorario;
    private javax.swing.JComboBox<Object> cbNomeCliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtCodigo;
    private com.toedter.calendar.JDateChooser txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextArea txtObservacao;
    private javax.swing.JTextField txtPorcentagemComissao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables


}
