/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import javax.swing.JOptionPane;
import negocio.Funcionario;
import persistencia.FuncionarioDAO;
import persistencia.IFuncionarioDAO;

/**
 *
 * @author joaos
 */
public class fmPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form fmPagamento
     */
    public fmPagamento() {
        initComponents();
        
        IFuncionarioDAO dao = new FuncionarioDAO();
        
        for (Funcionario f: dao.listarComFiltro(null, null, null, null))
        {
            cbFuncionario.addItem(f);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbFuncionario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtValorAPagar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtValorASerpago = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pagamento");
        setToolTipText("");

        jLabel1.setText("Funcionario");

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cbFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuncionarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor pendente (R$) :");

        txtValorAPagar.setText("0,00");
        txtValorAPagar.setToolTipText("");

        jLabel4.setText("Valor a ser pago (R$):");

        jScrollPane1.setViewportView(txtValorASerpago);

        jButton1.setText("Realizar Pagamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addComponent(txtValorAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtValorAPagar))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int valor = JOptionPane.showConfirmDialog(null, "Tem certeza que realizar o pagamento?", "Sistema Salão de Beleza", 1);
        if (valor ==0){
            if (txtValorASerpago.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Pagamento nao realizado pois o valor a ser pago está nulo!");
                return;
            }
            Funcionario func = (Funcionario) cbFuncionario.getSelectedItem();
            Float novovalor = func.getValorComissaoAPagar() - Float.parseFloat(txtValorASerpago.getText());
            IFuncionarioDAO funcionariodao = new FuncionarioDAO();
            funcionariodao.atualizaValorAPagar(novovalor, func.getId());
            JOptionPane.showMessageDialog(null, "Pagamento realizado!");
            atualizaValorDeTxtValorAPagar(func.getId());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atualizaValorDeTxtValorAPagar(Integer idFuncinario)
    {
        IFuncionarioDAO dao = new FuncionarioDAO();
        Funcionario func = dao.buscarPorID(idFuncinario);
        txtValorAPagar.setText(String.valueOf(func.getValorComissaoAPagar()));
    }
    private void cbFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuncionarioActionPerformed
        // TODO add your handling code here:
        Object aux = cbFuncionario.getSelectedItem();
        if (aux != null){            
            Funcionario func = (Funcionario) aux ;
            atualizaValorDeTxtValorAPagar(func.getId());
        }
        
        
        
    }//GEN-LAST:event_cbFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cbFuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtValorAPagar;
    private javax.swing.JTextPane txtValorASerpago;
    // End of variables declaration//GEN-END:variables
}
